### ISSUE TITLE
您好，请问不同数据集的图片的数量不一样，相同的batch size怎么联合训练

### ISSUE THREAD

**Issue by yfhdm** [Xiaoqi-Zhao-DLUT/Spider-UniCDSeg#4]

**Comment by yfhdm** [comment]
是用的cycle吗，比如zip(cycle(train_loader1),train_loader2)

**Comment by yfhdm** [comment]
没看到你发布的代码里面体现这个补齐操作

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@yfhdm 属于准备数据集之前的预处理。逐个任务循环遍历数据集，对齐到相同规模即可~~~。 具体操作，你想怎么实现都行~~~
