### ISSUE TITLE
Could you please provide the trained model weights?

### ISSUE THREAD

**Issue by lonelyqian** [Xiaoqi-Zhao-DLUT/Spider-UniCDSeg#5]
I want to perform inference with the trained model under a different setting to evaluate its adaptability and performance.

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@lonelyqian 
![image](https://github.com/user-attachments/assets/0faa9a77-ba2c-4141-a306-941755473fea)
here ~~~

**Comment by lonelyqian** [comment]
![image](https://github.com/user-attachments/assets/33f46651-c63e-4d05-b6f0-bce0f5fe976e)
![image](https://github.com/user-attachments/assets/8a46d031-f36c-47ee-9c1f-7e72de5c0be3)
The provided address seems to be incorrect

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@lonelyqian I have modified it. Thanks!
